name: 'aws-credentials-action'
description: 'Return and export AWS Credentials'
inputs:
  export:
    required: false
    default: 'true'
    description: 'Export AWS Credentials as environment variables'
  from:
    required: false
    default: 'auto'
    description: 'The source of the AWS Credentials. Can be "auto", "instance_metadata", "env_vars"'
outputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
  aws_session_token:
    description: 'AWS Session Token (if available)'
runs:
  using: 'node20'
  main: 'dist/index.js'
