name: 'aws-credentials-action'
description: 'Return and export AWS Credentials from various sources'
inputs:
  export:
    required: false
    default: 'true'
    description: 'Export AWS Credentials as environment variables'
  source:
    required: false
    default: 'auto'
    description: 'The source of the AWS Credentials. Can be "auto", "instance_metadata", "env_vars", "input'
  profile:
    required: false
    description: 'AWS Profile to use'
  region:
    required: false
    description: 'AWS Region to use'
  accessKeyId:
    required: false
    description: 'AWS Access Key ID (when source is "input")'
  secretAccessKey:
    required: false
    description: 'AWS Secret Access Key (when source is "input")'
  sessionToken:
    required: false
    description: 'AWS Session Token (if available, when source is "input")'
  assumeRoleArn:
    required: false
    description: 'The ARN of the role to assume'
  assumeRoleDurationSeconds:
    required: false
    description: 'The duration, in seconds, of the role assumption'
outputs:
  accessKeyId:
    description: 'AWS Access Key ID'
  secretAccessKey:
    description: 'AWS Secret Access Key'
  sessionToken:
    description: 'AWS Session Token (if available)'
runs:
  using: 'node20'
  main: 'dist/index.js'
