name: 'aws-credentials-action'
description: 'Fetch and export AWS Credentials'
inputs: { }
outputs:
  access_key_id:
    description: 'Returned AWS Access Key ID'
  secret_access_key:
    description: 'Returned AWS Secret Access Key'
  session_token:
    description: 'Returned AWS Session Token'
runs:
  using: 'node20'
  main: 'dist/index.js'
